default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: emd_challenge_user
  password: 123

development:
  <<: *default
  database: emd_challenge_development

test:
  <<: *default
  database: emd_challenge_test
